name: Gerar APK Android

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Clonar o código
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências do sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev

      - name: Instalar Buildozer e Cython
        run: |
          pip install --upgrade pip
          pip install buildozer cython virtualenv

      - name: Compilar o APK com Buildozer
        run: |
          buildozer android debug
        env:
          CI: 'true'

      - name: Disponibilizar o APK para Download
        uses: actions/upload-artifact@v4
        with:
          name: MeuJogo-APK
          path: bin/*.apk
